modelname:  baseline_attend_newv

# Data:
input_data_src: data/WMT14/en_src_cmp
input_data_trg: data/WMT14/fr_trg_cmp

# batch_size: 80
# valid_batch_size: 25
decode: greedy 
model: attention

# Loss
loss_version : ml

