modelname : combine_strat_rhamming_pool1_tsent016_a04_word_tword03_a05
model: attention

# Data:
input_data_src: data/WMT14/en_src
input_data_trg: data/WMT14/fr_trg

# batch_size: 50
# valid_batch_size: 15

# Loss:
loss_version : seq
reward : hamming
stratify_reward  : 1
tau_sent : .16
alpha_sent : 0.4
# lazy_rnn : 1
combine_loss : 1
tau_word : 0.3
alpha_word : 0.5
