modelname:  word_tword03_a05_attend

# Data:
input_data_src: data/WMT14/en_src
input_data_trg: data/WMT14/fr_trg
restart : 1

# batch_size: 10
# valid_batch_size: 20

# Loss
loss_version: word
alpha_word : 0.5
tau_word: 0.3
