label: 'IWSLT14 Baseline'
description: "IWSLT14 new baseline"

cell_size: 256
attn_size: 256
embedding_size: 128

cell_type: LSTM
weight_scale: 0.1

data_dir: data/IWSLT14
model_dir: models/IWSLT14/baseline
batch_size: 32

optimizer: adam
learning_rate: 0.001
learning_rate_decay_factor: 0.5
decay_every_n_epoch: 10

steps_per_checkpoint: 2000
steps_per_eval: 2000

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 20
max_epochs: 40

encoders:
  - name: de
    max_len: 45
    final_state: last_both

decoders:
  - name: en
    max_len: 47
    conditional_rnn: True
    pred_deep_layer: True

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
attn_dropout: 0.2
word_dropout: 0.2
initial_state_dropout: 0.2
