label: 'IWSLT14 Basic Word-based Model'

cell_size: 256
attn_size: 256
embedding_size: 128

cell_type: LSTM
weight_scale: 0.1

data_dir: data/IWSLT14_new
model_dir: models/IWSLT14/new/basic

batch_size: 32
optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 4000
steps_per_eval: 4000
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 20
max_steps: 200000
keep_best: 4
max_to_keep: 1

encoders:
  - name: de
    max_len: 45
    train_initial_states: False

decoders:
  - name: en
    max_len: 47
    pred_maxout_layer: False
    pred_embed_proj: True
    use_previous_word: False
    initial_state: zero
