modelname : combine_importance_qhamming_pool1_tsent013_rbleu4_tsent05_a03_word_idf_tword005_a03_wmt14
model: attention

# Data:
input_data_src: data/WMT14/en_src
input_data_trg: data/WMT14/fr_trg

batch_size: 40
valid_batch_size: 15
max_epochs : 5
# loss:
loss_version : seq
stratify_reward : 0
alpha_sent : 0.3

reward : bleu4
tau_sent : 0.5

importance_sampler : hamming
tau_sent_q : 0.13
limited_vocab_sub : 1

combine_loss : 1

similarity_matrix : data/WMT14/glove_w15d300.sim
rarity_matrix : data/WMT14/promote_rare.matrix
tau_word : 0.05
alpha_word : 0.3
promote_rarity : 1
