modelname:  word_idf_tword007_a04_iwslt14

# Data:
input_data_src: data/IWSLT14/de_src
input_data_trg: data/IWSLT14/en_trg
similarity_matrix : data/IWSLT14/glove_w15d300.sim
# config of Mixer (Ranzato et al.)
batch_size: 32
valid_batch_size: 32

learning_rate : 0.001
learning_rate_decay_every: 10
learning_rate_decay_rate : 0.5
max_epochs : 40

dim_word_src : 128
rnn_size_src : 256
num_layers_src : 1

dim_word_trg : 128
rnn_size_trg : 256
num_layers_trg : 1


decode: greedy 
model: attention

# Loss
loss_version: word
alpha_word : 0.4
tau_word: 0.07
promote_rarity : 1
rarity_matrix : data/IWSLT14/promote_rare.matrix
